# Generated by Django 3.2.6 on 2021-08-25 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('accept_responses', models.BooleanField(default=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FormObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.profile')),
                ('form_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.formparent')),
            ],
        ),
        migrations.CreateModel(
            name='FormIntegerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=200)),
                ('field_data', models.BigIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.CharField(default='int', max_length=30)),
                ('form_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.formobject')),
            ],
        ),
        migrations.CreateModel(
            name='FormFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=200)),
                ('field_data', models.FileField(upload_to='fileData')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.CharField(default='file', max_length=30)),
                ('form_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.formobject')),
            ],
        ),
        migrations.CreateModel(
            name='FormDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('character_field', models.BooleanField(default=False)),
                ('big_text_field', models.BooleanField(default=False)),
                ('integer_field', models.BooleanField(default=False)),
                ('file_field', models.BooleanField(default=False)),
                ('form_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.formparent')),
            ],
        ),
        migrations.CreateModel(
            name='FormCharacterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=200)),
                ('field_data', models.CharField(max_length=400)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.CharField(default='char', max_length=30)),
                ('form_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.formobject')),
            ],
        ),
        migrations.CreateModel(
            name='FormBigTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, max_length=200)),
                ('field_data', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_of', models.CharField(default='txt', max_length=30)),
                ('form_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.formobject')),
            ],
        ),
    ]
